site:
    title: PHP UserGroup Leipzig
    description: PHP Usergroup Leipzig - Austausch über Neuigkeiten, Fakten und Best Practice zur Programmiersprache PHP
    author: PHPUGL Team
    copyright: PHP Usergroup Leipzig
    keywords: PHP,Leipzig,Usergroup,Best Practice,Treffen
    language: de
    pretty_urls: true
    posts_fs: shallow
    posts_per_page: 10
    date_format: 'd.m.Y'
    members:
        bergo: https://avatars.githubusercontent.com/u/619785?v=3&s=120
        bitundpixel: https://avatars.githubusercontent.com/u/205191?v=3&s=120
        cweiske: https://avatars.githubusercontent.com/u/59036?v=3&s=120
        mikewink: https://avatars.githubusercontent.com/u/183511?v=3&s=120
        nogo: https://avatars.githubusercontent.com/u/305163?v=3&s=120
        quafzi: https://avatars.githubusercontent.com/u/164261?v=3&s=120
        ThomasJez: https://avatars.githubusercontent.com/u/1399641?v=3&s=120
        tqmz: https://avatars.githubusercontent.com/u/121209?v=3&s=120
        thyseus: https://avatars.githubusercontent.com/u/654271?v=3&s=120
        bascht: https://avatars.githubusercontent.com/u/51264?v=3&s=120
        ChrisChinchilla: https://avatars.githubusercontent.com/u/42080?v=3&s=120
        der-On: https://avatars.githubusercontent.com/u/359399?v=3&s=120

markdown:
    use_markdown_extra: true

smartypants:
    enable: true

baker:
    config_variants:
        default:
            site:
                root: https://phpugl.de
    skip_patterns:
        - /^bin/
        - /^vendor/
        - /^composer.*/
        - /^index.php/
